# config.py
import multiprocessing as mp

# --- General Configuration ---
PLACE_NAME = "Leuven, Belgium"
NETWORK_TYPE = "all_public"
RASTER_FILE_PATH = "./DTM_20m.tif" # User must ensure this path is correct
RASTER_BAND = 1
NUM_CPUS = min(mp.cpu_count(), 4)

# --- Physiological Model Parameters ---
USER_VO2MAX = 45.0
USER_EFFORT_LEVEL = 3

# --- Visualization Control ---
# Set VISUALIZATION_TARGET to the exact column name string you want to visualize.
# Examples of valid column names (generated by the scripts):
# 'grade_abs_pct', 'merit_edge', 'merit_edge_per_minute', 'length', 'time_min_edge', etc.
VISUALIZATION_TARGET = 'merit_edge_per_minute' # This will be the column visualized

# --- General Visualization Parameters ---
VIS_COLORMAP = 'YlOrRd' # Fixed colormap for all visualizations

# --- Output File Names ---
INTERACTIVE_MAP_FILENAME_TEMPLATE = "interactive_map_{place_short}_{attribute}_auto_range.html"
BASIC_MAP_FILENAME_TEMPLATE = "interactive_map_no_attribute_data_{place_short}.html"